package com.github.kingbbode.scheduler.domain;

import lombok.Getter;
import lombok.Setter;

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * QrtzBlobTriggers generated by hbm2java
 */
@Getter
@Setter
@Entity
@Table(name="QRTZ_BLOB_TRIGGERS")
public class QrtzBlobTriggers  implements java.io.Serializable {

    @EmbeddedId
    private QrtzTriggersId id;

    @Column(name="BLOB_DATA")
    private byte[] blobData;

}


