package com.github.kingbbode.scheduler.domain;

import lombok.*;

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * QrtzSimpleTriggers generated by hbm2java
 */
@Getter
@Setter
@Entity
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Table(name="QRTZ_SIMPLE_TRIGGERS")
public class QrtzSimpleTriggers  implements java.io.Serializable {

    @EmbeddedId
    private QrtzTriggersId id;

    @Column(name="REPEAT_COUNT", nullable=false)
    private long repeatCount;

    @Column(name="REPEAT_INTERVAL", nullable=false)
    private long repeatInterval;

    @Column(name="TIMES_TRIGGERED", nullable=false)
    private long timesTriggered;
}


