package com.github.kingbbode.scheduler.domain;

import com.github.kingbbode.scheduler.dto.SchedulerResponse;
import com.github.kingbbode.scheduler.utils.JobDataMapConverter;
import lombok.*;
import org.quartz.JobDataMap;

import javax.persistence.*;
import java.time.LocalDateTime;
import java.time.ZoneId;

/**
 * QrtzTriggers generated by hbm2java
 */
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Builder
@Entity
@Table(name="QRTZ_SIMPLE_TRIGGERS_HISTORY")
public class QrtzSimpleTriggersHistory {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "IDX")
    private Long idx;

    @Column(name="SCHED_NAME", nullable=false, length=120)
    private String schedName;

    @Column(name="JOB_NAME", nullable=false, length=200)
    private String jobName;

    @Column(name="TRIGGER_NAME", nullable=false, length=200)
    private String triggerName;

    @Column(name="`REPEAT`")
    private int repeat;

    @Column(name="`INTERVAL`")
    private int repeatInterval;

    @Column(name="EXECUTOR", nullable=false, length=50)
    private String executor;

    @Column(name="EXECUTE_DATE")
    private LocalDateTime executeDateTime;
    
    @Column(name = "JOB_DATA")
    private JobDataMap jobDataMap;

    @SuppressWarnings("unchecked")
    public SchedulerResponse.SimpleTrigger toSimpleTrigger() {
        return SchedulerResponse.SimpleTrigger.builder()
                .name(this.triggerName)
                .repeat(this.repeat)
                .repeatInterval(this.repeatInterval)
                .executor(this.executor)
                .executeTimeStamp(this.executeDateTime.atZone(ZoneId.systemDefault()).toInstant().toEpochMilli())
                .params(JobDataMapConverter.convertJobDataToForceMap(this.jobDataMap))
                .build();
    }
}


