package com.github.kingbbode.execution.domain;

import lombok.Getter;
import lombok.Setter;

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

/**
 * BatchJobInstance generated by hbm2java
 */
@Getter
@Setter
@Entity
@Table(name="BATCH_JOB_INSTANCE", uniqueConstraints = @UniqueConstraint(columnNames={"JOB_NAME", "JOB_KEY"}))
public class BatchJobInstance  implements java.io.Serializable {

    @Id
    @Column(name="JOB_INSTANCE_ID", unique=true, nullable=false)
    private long jobInstanceId;

    @Version
    @Column(name="VERSION")
    private Long version;

    @Column(name="JOB_NAME", nullable=false, length=100)
    private String jobName;

    @Column(name="JOB_KEY", nullable=false, length=32)
    private String jobKey;

    @OneToMany(fetch=FetchType.LAZY, mappedBy="batchJobInstance")
    private Set<BatchJobExecution> batchJobExecutions = new HashSet<>(0);

}


